### ISSUE TITLE
Replace dropdown menu with graphics as report types

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/duwamish#142] opened 2015-09-26 21:34 UTC
The goal of this issue ticket is to convert the "type of report" drop down menu into a button interface that functions like this:

![report-buckets](https://cloud.githubusercontent.com/assets/4207017/8736826/d5e4ac9c-2bd0-11e5-9dc6-8635520914f6.png)

Take a look at this [Demo](https://civiclaboratories.com/demo/bike-network-improvements) for a similar example.

You'll see that instead of a dropdown menu, it prompts the user with a simple set of pretty buttons. Each button has a conditional set of form fields attached to it which only display depending on which button is selected.

This is superior to the current "submit a report" [form](http://heyduwamish.org/place/new) on Hey Duwamish because it gets rid of the drop down option for "type of report" which users tend to ignore or not understand.

The code for the example [demo](https://civiclaboratories.com/demo/bike-network-improvements) is available as a Planbox theme [here](https://github.com/openplans/planbox-themes/tree/gh-pages/bike-network-improvements)

The goal is to borrow the [place-form.html](https://github.com/openplans/planbox-themes/blob/gh-pages/bike-network-improvements/jstemplates/place-form.html) from the "Bike Network Improvements" Planbox Theme and use it in the [place-form.html](https://github.com/smartercleanup/duwamish/blob/master/src/flavors/duwamish_flavor/jstemplates/place-form.html) on Hey Duwamish.

This issue should help with the implementation of #94 and #127

**Comment by futuresoup** [comment] 2015-11-26 02:23
Closing this, as it feels like a duplicate of #127

**Closed by futuresoup** 2015-11-26 02:23 UTC
Labels: 1 - Ready
