### ISSUE TITLE
Setup CSS pre-processor (SASS, LESS, or Compass)

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/duwamish#232] opened 2016-01-20 20:46 UTC
Our CSS is gigantic. We need a pre-processor to better organize and compile.

There's SASS
http://sass-lang.com/install

Compass
http://compass-style.org

LESS
http://lesscss.org/

And GUI apps like Koala to manage them:
http://koala-app.com/

**Comment by LukeSwart** [comment] 2016-02-12 23:45
Closing this issue, because it is a duplicate of #184

**Closed by LukeSwart** 2016-02-12 23:45 UTC
Labels: css/html, enhancement
